package com.cccxm.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cccxm.dao.Tongue;
import com.cccxm.dao.TongueLib;

import com.cccxm.dao.TongueDao;
import com.cccxm.dao.TongueLibDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tongueDaoConfig;
    private final DaoConfig tongueLibDaoConfig;

    private final TongueDao tongueDao;
    private final TongueLibDao tongueLibDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tongueDaoConfig = daoConfigMap.get(TongueDao.class).clone();
        tongueDaoConfig.initIdentityScope(type);

        tongueLibDaoConfig = daoConfigMap.get(TongueLibDao.class).clone();
        tongueLibDaoConfig.initIdentityScope(type);

        tongueDao = new TongueDao(tongueDaoConfig, this);
        tongueLibDao = new TongueLibDao(tongueLibDaoConfig, this);

        registerDao(Tongue.class, tongueDao);
        registerDao(TongueLib.class, tongueLibDao);
    }
    
    public void clear() {
        tongueDaoConfig.clearIdentityScope();
        tongueLibDaoConfig.clearIdentityScope();
    }

    public TongueDao getTongueDao() {
        return tongueDao;
    }

    public TongueLibDao getTongueLibDao() {
        return tongueLibDao;
    }

}
