package com.cccxm.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "TONGUE".
 */
@Entity
public class Tongue {

    @Id
    private Long id;
    private int lib_id;

    @NotNull
    private String en;

    @NotNull
    private String ch;
    private java.util.Date next;
    private Integer progress;

    @Generated
    public Tongue() {
    }

    public Tongue(Long id) {
        this.id = id;
    }

    @Generated
    public Tongue(Long id, int lib_id, String en, String ch, java.util.Date next, Integer progress) {
        this.id = id;
        this.lib_id = lib_id;
        this.en = en;
        this.ch = ch;
        this.next = next;
        this.progress = progress;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getLib_id() {
        return lib_id;
    }

    public void setLib_id(int lib_id) {
        this.lib_id = lib_id;
    }

    @NotNull
    public String getEn() {
        return en;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEn(@NotNull String en) {
        this.en = en;
    }

    @NotNull
    public String getCh() {
        return ch;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCh(@NotNull String ch) {
        this.ch = ch;
    }

    public java.util.Date getNext() {
        return next;
    }

    public void setNext(java.util.Date next) {
        this.next = next;
    }

    public Integer getProgress() {
        return progress;
    }

    public void setProgress(Integer progress) {
        this.progress = progress;
    }

}
