package com.cccxm.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TONGUE_LIB".
*/
public class TongueLibDao extends AbstractDao<TongueLib, Long> {

    public static final String TABLENAME = "TONGUE_LIB";

    /**
     * Properties of entity TongueLib.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Lib_category = new Property(1, Integer.class, "lib_category", false, "LIB_CATEGORY");
        public final static Property Lib_name = new Property(2, String.class, "lib_name", false, "LIB_NAME");
        public final static Property Level = new Property(3, Integer.class, "level", false, "LEVEL");
        public final static Property Score = new Property(4, Integer.class, "score", false, "SCORE");
        public final static Property Uri = new Property(5, String.class, "uri", false, "URI");
        public final static Property Count = new Property(6, Integer.class, "count", false, "COUNT");
    }


    public TongueLibDao(DaoConfig config) {
        super(config);
    }
    
    public TongueLibDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TONGUE_LIB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"LIB_CATEGORY\" INTEGER," + // 1: lib_category
                "\"LIB_NAME\" TEXT NOT NULL ," + // 2: lib_name
                "\"LEVEL\" INTEGER," + // 3: level
                "\"SCORE\" INTEGER," + // 4: score
                "\"URI\" TEXT," + // 5: uri
                "\"COUNT\" INTEGER);"); // 6: count
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TONGUE_LIB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TongueLib entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer lib_category = entity.getLib_category();
        if (lib_category != null) {
            stmt.bindLong(2, lib_category);
        }
        stmt.bindString(3, entity.getLib_name());
 
        Integer level = entity.getLevel();
        if (level != null) {
            stmt.bindLong(4, level);
        }
 
        Integer score = entity.getScore();
        if (score != null) {
            stmt.bindLong(5, score);
        }
 
        String uri = entity.getUri();
        if (uri != null) {
            stmt.bindString(6, uri);
        }
 
        Integer count = entity.getCount();
        if (count != null) {
            stmt.bindLong(7, count);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TongueLib entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer lib_category = entity.getLib_category();
        if (lib_category != null) {
            stmt.bindLong(2, lib_category);
        }
        stmt.bindString(3, entity.getLib_name());
 
        Integer level = entity.getLevel();
        if (level != null) {
            stmt.bindLong(4, level);
        }
 
        Integer score = entity.getScore();
        if (score != null) {
            stmt.bindLong(5, score);
        }
 
        String uri = entity.getUri();
        if (uri != null) {
            stmt.bindString(6, uri);
        }
 
        Integer count = entity.getCount();
        if (count != null) {
            stmt.bindLong(7, count);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TongueLib readEntity(Cursor cursor, int offset) {
        TongueLib entity = new TongueLib( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // lib_category
            cursor.getString(offset + 2), // lib_name
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // level
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // score
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // uri
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6) // count
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TongueLib entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLib_category(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setLib_name(cursor.getString(offset + 2));
        entity.setLevel(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setScore(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setUri(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCount(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TongueLib entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TongueLib entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TongueLib entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
