package com.cccxm.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "TONGUE_LIB".
 */
@Entity
public class TongueLib {

    @Id
    private Long id;

    @NotNull
    private String lib_name;
    private Integer level;
    private Integer score;
    private String uri;
    private Integer count;
    private Boolean submit;

    @Generated
    public TongueLib() {
    }

    public TongueLib(Long id) {
        this.id = id;
    }

    @Generated
    public TongueLib(Long id, String lib_name, Integer level, Integer score, String uri, Integer count, Boolean submit) {
        this.id = id;
        this.lib_name = lib_name;
        this.level = level;
        this.score = score;
        this.uri = uri;
        this.count = count;
        this.submit = submit;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getLib_name() {
        return lib_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLib_name(@NotNull String lib_name) {
        this.lib_name = lib_name;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Boolean getSubmit() {
        return submit;
    }

    public void setSubmit(Boolean submit) {
        this.submit = submit;
    }

}
